name: PHP Composer

on:
  workflow_dispatch:
   inputs:
      environment:
        description: 'Environment to run tests against'
        default: sandbox
        type: choice
        options:
          - sandbox
          - prod
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      env:
        SECRET: "${{ github.event.inputs.environment == 'prod' && secrets.PRODSECRET || secrets.SANDBOXSECRET}}"
      run: php -d secret=$SECRET -d env=${{ github.event.inputs.environment }} phpunit.phar ClientTest.php
